;
; The sequence of triangle numbers is generated by adding the natural numbers.
; So the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
; The first ten terms would be:
;
; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;
; Let us list the factors of the first seven triangle numbers:
;
     ;1: 1
     ;3: 1,3
     ;6: 1,2,3,6
    ;10: 1,2,5,10
    ;15: 1,3,5,15
    ;21: 1,3,7,21
    ;28: 1,2,4,7,14,28
;
; We can see that 28 is the first triangle number to have over five divisors.
;
; What is the value of the first triangle number to have over five hundred divisors?
;

(ns problem12
  (:use clojure.set)
  (:use clojure.test))

  ;(:require clojure.contrib.profile))

(set! *warn-on-reflection* true)

(defn dividers
  [x]
  (filter #(zero? (rem x %)) (range 1 (Math/sqrt x))))

(def triangles
  (lazy-seq
    (cons 0 (map + triangles (iterate inc 1)))))

(defn solve
  [n]
  (first (filter #(> (* 2 (count (dividers %))) n) triangles)))

; test
;; (is (= 28 (solve 5)))

;; ; 50 25200
;; (println (time (solve 500)))
